# Datasource
spring.datasource.url=jdbc:postgresql://localhost:5432/wallet_db
spring.datasource.username=himanshukumar
spring.datasource.password=postgres

# JPA
spring.jpa.hibernate.ddl-auto=validate

# Flyway
spring.flyway.enabled=true

# SQL Initialization
spring.sql.init.mode=never

# Server
server.port=8080